from cannings.offspring_distribution import average
from cannings.offspring_distribution import generate_offspring
from cannings.diffusion import nb_next_generation
from cannings.fixation import fixation
